/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeMessagesIndexRouteImport } from './routes/home/messages/index'
import { Route as HomeHelpIndexRouteImport } from './routes/home/help/index'
import { Route as HomeDashboardIndexRouteImport } from './routes/home/dashboard/index'
import { Route as HomeCalendarIndexRouteImport } from './routes/home/calendar/index'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeMessagesIndexRoute = HomeMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHelpIndexRoute = HomeHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeDashboardIndexRoute = HomeDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCalendarIndexRoute = HomeCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/calendar': typeof HomeCalendarIndexRoute
  '/home/dashboard': typeof HomeDashboardIndexRoute
  '/home/help': typeof HomeHelpIndexRoute
  '/home/messages': typeof HomeMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/calendar': typeof HomeCalendarIndexRoute
  '/home/dashboard': typeof HomeDashboardIndexRoute
  '/home/help': typeof HomeHelpIndexRoute
  '/home/messages': typeof HomeMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/home/calendar/': typeof HomeCalendarIndexRoute
  '/home/dashboard/': typeof HomeDashboardIndexRoute
  '/home/help/': typeof HomeHelpIndexRoute
  '/home/messages/': typeof HomeMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/home/calendar'
    | '/home/dashboard'
    | '/home/help'
    | '/home/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/home/calendar'
    | '/home/dashboard'
    | '/home/help'
    | '/home/messages'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/home/calendar/'
    | '/home/dashboard/'
    | '/home/help/'
    | '/home/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/messages/': {
      id: '/home/messages/'
      path: '/messages'
      fullPath: '/home/messages'
      preLoaderRoute: typeof HomeMessagesIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/help/': {
      id: '/home/help/'
      path: '/help'
      fullPath: '/home/help'
      preLoaderRoute: typeof HomeHelpIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/dashboard/': {
      id: '/home/dashboard/'
      path: '/dashboard'
      fullPath: '/home/dashboard'
      preLoaderRoute: typeof HomeDashboardIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/calendar/': {
      id: '/home/calendar/'
      path: '/calendar'
      fullPath: '/home/calendar'
      preLoaderRoute: typeof HomeCalendarIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeCalendarIndexRoute: typeof HomeCalendarIndexRoute
  HomeDashboardIndexRoute: typeof HomeDashboardIndexRoute
  HomeHelpIndexRoute: typeof HomeHelpIndexRoute
  HomeMessagesIndexRoute: typeof HomeMessagesIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeCalendarIndexRoute: HomeCalendarIndexRoute,
  HomeDashboardIndexRoute: HomeDashboardIndexRoute,
  HomeHelpIndexRoute: HomeHelpIndexRoute,
  HomeMessagesIndexRoute: HomeMessagesIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
